# Generated by Django 4.2.11 on 2024-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0002_appuser_is_staff_alter_appuser_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                ("pack_id", models.AutoField(primary_key=True, serialize=False)),
                ("sender", models.CharField(max_length=100)),
                ("receiver", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                ("sender_city", models.CharField(max_length=100)),
                ("destination_city", models.CharField(max_length=100)),
                ("tracking", models.BooleanField(default=False)),
                ("status", models.CharField(max_length=100)),
            ],
        ),
    ]
